matrix:
  include:
  - env: sys=debian-stretch dir=docker-ce/components/packaging/deb bin_dir=docker-ce/components/packaging/deb/debbuild/
  - env: sys=ubuntu-xenial dir=docker-ce/components/packaging/deb bin_dir=docker-ce/components/packaging/deb/debbuild/
  - env: sys=ubuntu-bionic dir=docker-ce/components/packaging/deb bin_dir=docker-ce/components/packaging/deb/debbuild/
  - env: sys=centos dir=docker-ce/components/packaging/rpm bin_dir=docker-ce/components/packaging/rpm/rpmbuild/RPMS/

os: linux-ppc64le
sudo: required
services: docker

script:
   - python3 ftp_version.py
   - github_version=$(cat github_version.txt)
   - ftp_version=$(cat ftp_version.txt)
   - del_version=$(cat delete_version.txt)
   - create_dir=$(cat create_dir.txt)
   - sudo apt install -y lftp
   - wget https://github.com/docker/docker-ce/archive/v$github_version.zip
   - unzip v$github_version.zip
   - mv docker-ce-$github_version docker-ce
   - cd $dir
   - VERSION=$github_version make $sys
   - if [[ $sys == "centos" ]]; then mv rpmbuild/RPMS/ppc64le rpmbuild/RPMS/centos-7 fi
   - if [[ $create_dir > -1 ]]; then lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; mkdir /ppc64el/docker/version-$github_version" fi
   - cd ../../../../
   - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; mirror -R $bin_dir /ppc64el/docker/version-$github_version" 
