matrix:
  include:
    - env: version=18.09.0 build_version=18.09.0-ce

os: linux-ppc64le
sudo: required
services: docker

script:
  - sudo apt install lftp
  - wget https://github.com/docker/docker-ce/archive/v$version.zip
  - unzip v$version.zip
  - mv docker-ce-$version docker-ce
  - cd docker-ce
  - cd components/packaging/rpm
  - VERSION=$build_version make centos
  - cd ../../../
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; mkdir /ppc64el/docker/rpm/$version"
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; mirror -R components/packaging/rpm/rpmbuild/RPMS/ppc64le/ /ppc64el/docker/rpm/$version"
  - cd components/packaging/deb
  - VERSION=$build_version make ubuntu-xenial
  - VERSION=$build_version make ubuntu-bionic 
  - cd ../../../
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; mkdir /ppc64el/docker/deb/$version"
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; mirror -R components/packaging/deb/debbuild/ /ppc64el/docker/deb/$version"

 
