matrix:
  include:
  - env: version=18.09.4 sys=debian-stretch
  - env: version=18.09.3 sys=debian-stretch
  - env: version=18.09.2 sys=debian-stretch
  - env: version=18.09.1 sys=debian-stretch
  - env: version=18.09.0 sys=debian-stretch 
  - env: version=18.09.4 sys=ubuntu-xenial 
  - env: version=18.09.3 sys=ubuntu-xenial 
  - env: version=18.09.2 sys=ubuntu-xenial
  - env: version=18.09.1 sys=ubuntu-xenial
  - env: version=18.09.0 sys=ubuntu-xenial
  - env: version=18.09.4 sys=ubuntu-bionic
  - env: version=18.09.3 sys=ubuntu-bionic
  - env: version=18.09.2 sys=ubuntu-bionic
  - env: version=18.09.1 sys=ubuntu-bionic
  - env: version=18.09.0 sys=ubuntu-bionic
  #- env: version=18.09.4 sys=centos dir=rpm
  #- env: version=18.09.3 sys=centos dir=rpm
  #- env: version=18.09.2 sys=centos dir=rpm
  #- env: version=18.09.1 sys=centos dir=rpm
  #- env: version=18.09.0 sys=centos dir=rpm

os: linux-ppc64le
sudo: required
services: docker

script:
  - sudo apt install -y lftp
  - git clone https://github.com/Unicamp-OpenPower/docker-ce
  - cd docker-ce/components/packaging/deb
  - VERSION=$version make $sys
  - ls
  - cd debbuild
  - ls
  - cd ..
  - cd ../../../
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; mirror -R components/packaging/deb/debbuild/debian-stretch /ppc64el/docker/$version"
