os: linux-ppc64le
sudo: required
services: docker

script:
  - git clone https://github.com/Unicamp-OpenPower/docker-ce
  - cd ./docker-ce
  - cd components/packaging/rpm
  - git clone https://github.com/docker/docker-ce.git
  - make ENGINE_DIR=docker-ce/components/engine CLI_DIR=docker-ce/components/cli rpm
