#matrix:
#  include:
#  - env: sys=debian-stretch dir=docker-ce/components/packaging/deb bin_dir=docker-ce/components/packaging/deb/debian-stretch/
#  - env: sys=ubuntu-xenial dir=docker-ce/components/packaging/deb bin_dir=docker-ce/components/packaging/deb/ubuntu-xenial/
#  - env: sys=ubuntu-bionic dir=docker-ce/components/packaging/deb bin_dir=docker-ce/components/packaging/deb/ubuntu-bionic/
#  - env: sys=centos dir=docker-ce/components/packaging/rpm bin_dir=docker-ce/components/packaging/rpm/rpmbuild/RPMS/ppc64le/

os: linux-ppc64le
sudo: required
services: docker

script:
   - python3 ftp_version.py
   - github_version=$(cat github_version.txt)
   - ftp_version=$(cat ftp_version.txt)
   - del_version=$(cat delete_version.txt)
   - sudo apt install -y lftp
   - wget https://github.com/docker/docker-ce/archive/v$github_version.zip
   - unzip v$github_version.zip
   - mv docker-ce-$github_version docker-ce
   - cd docker-ce/components/packaging/deb
   - echo $build_version
   - VERSION=$build_version make debian-stretch
   - cd ../../../../
   - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; mkdir /ppc64el/docker/version-$github_version"
   - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; mirror -R docker-ce/components/packaging/deb/debian-stretch/ /ppc64el/docker/version-$github_version"
