os: linux-ppc64le
sudo: required
services: docker

script:
  - sudo apt install -y lftp
  - git clone https://github.com/Unicamp-OpenPower/docker-ce
  - cd docker-ce
  - cd components/packaging/deb
  - git clone https://github.com/docker/docker-ce.git
  - VERSION=18.09.0 make debian-stretch
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; mkdir /ppc64el/docker/teste"
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; mirror -R debbuild/ /ppc64el/docker/teste"
