matrix:
  include:
    - env: version=18.09.4-rc1
    - env: version=18.09.3
    - env: version=18.09.3-rc1
    - env: version=18.06.3-ce
    - env: version=18.09.2
    - env: version=18.06.2-ce
    - env: version=18.09.1
    - env: version=18.09.1-rc1
    - env: version=18.09.1-beta2

os: linux-ppc64le
sudo: required
services: docker

script:
  - wget https://github.com/docker/docker-ce/archive/v$version.zip
  - unzip v$version.zip
  - mv docker-ce-$version docker-ce
  - cd docker-ce
  - cd components/packaging/rpm
  - VERSION=$version-ce make centos
  - cd ../../../
  - cd components/packaging/deb
  - VERSION=$version-ce make ubuntu-xenial
  - VERSION=$version-ce make ubuntu-bionic 
  - cd ../../../
  - ls components/packaging/deb/debbuild/
  - ls components/packaging/rpm/rpmbuild/RPMS/ppc64le/
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; mirror -R --continue --reverse --no-empty-dirs --no-perms components/packaging/deb/debbuild/ /ppc64el/docker/deb"
  - lftp -c "open -u $USER,$PASS ftp://oplab9.parqtec.unicamp.br; mirror -R --continue --reverse --no-empty-dirs --no-perms components/packaging/rpm/rpmbuild/RPMS/ppc64le/ /ppc64el/docker/rpm"

